# Paleta: tokyonight night (matchea wezterm, tmux, nvim y borders)
format = """\
[](fg:#9ece6a)\
[󰀵 ](bg:#9ece6a fg:#000000)\
[](fg:#9ece6a bg:#16161e)\
$time\
[](fg:#16161e bg:#7aa2f7)\
$directory\
[](fg:#7aa2f7 bg:#e0af68)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#e0af68)\
$cmd_duration\
$character\
"""

[directory]
format = "[ $path ]($style)"
style = "fg:#000000 bg:#7aa2f7"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:#000000 bg:#e0af68"

[git_status]
format = '[$all_status]($style)'
style = "fg:#000000 bg:#e0af68"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#000000 bg:#e0af68"
deleted_style = "fg:#f7768e bg:#000000"
disabled = false

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:#e0af68"

[character]
success_symbol = '[ ➜](bold #9ece6a) '
error_symbol = '[ ✗](#f7768e) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ 󱑍 $time ](bg:#16161e fg:#7dcfff)'
