#!/bin/bash
# JankyBorders — borde en la ventana focused (colores tokyonight night)

options=(
	style=round
	width=6.0
	hidpi=on
	active_color=0xff7aa2f7
	inactive_color=0xff1a1b26
)

borders "${options[@]}"
